repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0 # Use the latest version
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs

  - repo: https://github.com/bridgecrewio/checkov
    rev: v3.0.0 # Use the latest version
    hooks:
      - id: checkov
