repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs

  - repo: https://github.com/bridgecrewio/checkov
    rev: b3deb288bfed51c040cfa460be609404945d72c2 # only latest commit hash works
    hooks:
      - id: checkov
        args: ["--download-external-modules", "true"]
